# Generated by Django 3.2 on 2021-12-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_rename_price_product_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
    ]
