# Generated by Django 3.2 on 2022-01-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_contactlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='email',
        ),
    ]
