# Generated by Django 3.2 on 2022-01-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0007_rename_title_contactlist_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactList',
            new_name='Contact',
        ),
    ]
